lesson1
1DarkSpectre1/GeekBrains pull request #14
Opened 2021-06-24 16:46 UTC by 1DarkSpectre1

2021-06-24 18:45 UTC, vladimir-shmidt requested changes
в целом код нормальный
асинк где есть правильный
есть пара замечаний для улучшения

2021-06-24 18:45 UTC, vladimir-shmidt commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +            File.WriteAllText(filename, "");
запись в файл такая же операция ввода вывода так что может быть выполнена асинхронно

2021-06-24 18:45 UTC, vladimir-shmidt commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +
лишние строки

2021-06-24 18:45 UTC, vladimir-shmidt commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +            for (int i = 1; i < 11; i++)
номера не по заданию

2021-06-24 18:45 UTC, vladimir-shmidt commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +                    File.AppendAllText(filename,Convert.ToString( post.userId));
AppendAllText каждый раз будет открывать файл писать и закрывать файл
операция дорогая
стоит сделать запись одним действием
запись может быть асинхронной
для записи лучше использовать FileStream

2021-06-24 18:45 UTC, vladimir-shmidt commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +                catch (HttpRequestException e)
обработкой ошибок обычно должна заниматься вызывающая сторона если при этом от такой ошибки не возможно востановится

2021-07-05 14:50 UTC, vladimir-shmidt requested changes
в целом ок
но нужно сделать несколько изменений

2021-07-11 06:20 UTC, 1DarkSpectre1 commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +            File.WriteAllText(filename, "");
Здесь я решил оставить так. Если добавить асинхронность то может произойти сначала запись, а потом очистка

2021-07-11 06:22 UTC, 1DarkSpectre1 commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +                catch (HttpRequestException e)
Здесь совсем стоило убрать обработку ошибок? (Мне кажется это не совсем корректно)

2021-07-12 09:49 UTC, vladimir-shmidt approved these changes
С точки зрения задачи по работе с async справился. 
С точки зрения совместной работы над улучшением кода и принятии правок с аргументированным обоснованием не справился.
Решение на обучающей платформе принимается

2021-07-12 09:49 UTC, vladimir-shmidt commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +            File.WriteAllText(filename, "");
такого быть не может. Асинхронный код != многопоточный

2021-07-12 09:49 UTC, vladimir-shmidt commented on ASP.NET Core Веб Приложение/GetAsync/GetAsync/GetAsync/Program.cs
> +                catch (HttpRequestException e)
смысл обработки исключений заключаетс не в простом указании try в каждом месте. Обрабатывать ошибки должен тот код который сможет восстановить работу после появляения ошибки.

Что должен сделать GetAndWrite после ошибки записи в файл? или после ошибки скачивания? Правильный ответ ничего. Задача метода заключается в скачивании и записи. Метод ничего не сможет сделать кроме как заверешится после неудачи. В свою очередь код вызывающий GetAndWrite может попробовать заново вызвать GetAndWrite или всячески пробовать продолжить работу неудачную, банальным пропуском пробленого GetAndWrite.
Если вспомнить про solid то метод нарушает пару принципов. Например он и читает и пишет и ошибки обрабатывает

2021-07-12 15:49 UTC, merged